# This workflow deploys the current model to PyPI after a new release is created on GitHub.

name: Test Python Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Test framework # instantiate testing job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # checkout the repo
      - name: Install dependencies  # install all dependencies in requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Execute tests  # execute tests in tests/
        run: |
          cd neuralforge
          python ../tests/test_framework.py
          cd ..
