on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: TestFramework
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3     # checkout the repo
      - run: python scr/test_framework.py
